workflows:
  build-android-ios:
    name: Build Android and iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUILD_MODE: release
    scripts:
      - name: Clean previous builds
        script: flutter clean

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android APK
        script: flutter build apk --release

      - name: Build iOS (debug for now)
        script: flutter build ios --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - mostafahassaan93@gmail.com # ← غيّر ده لبريدك الحقيقي
